name: myapplib
description: A collection of classes and function useful to develop Flutter apps
version: 0.0.1
homepage: none
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.0
  slang_build_runner: ^3.32.0

